apiVersion: batch/v1
kind: CronJob
metadata:
  name: my-cronjob
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: print
            image: busybox:stable
            command: ["echo","Muhammad Fayyaz"]
          restartPolicy: Never
      backoffLimist: 4
      activeDeadlineSeconds: 10  
